#!/bin/bash
npm install
npm run build
rm -rf jasmine
mkdir jasmine
cp -r assets jasmine
cp -r component jasmine
cp -r core jasmine
cp ./*.php jasmine
cp LICENSE jasmine
cp README.md jasmine
cp screenshot.png jasmine
zip -r jasmine.zip jasmine
rm -rf jasmine
